### ISSUE TITLE
WR841N 4mb flash

### ISSUE THREAD

**Issue by iiikary** [BastelPichi/MineCryptoOnWifiRouter#5]
how to install python3 with the router WR841N (openwrt) with only 4mb of flash

**Comment by BastelPichi** [comment]
Hey,
This case is a bit more complicated. You may, if your router has a usb port, install python on a usb stick. [Heres](https://shipit.dev/posts/installing-python-in-openwrt-on-usb-storage.html) a guide. If there is no usb, im afraid you cant do anything.

**Comment by iiikary** [comment]
![image](https://user-images.githubusercontent.com/65255663/148313124-a834e804-afd2-4d64-8e2f-6a30c4c2fbab.png)

**Comment by iiikary** [comment]
i managed to install python3 and coreutils-nohup, and the final version of miner.py. but when I run it gives me the following error, the router has internet and navigates

**Comment by BastelPichi** [comment]
can you try running the following command on your router and sending the output here? 
```python3 -c "import json; import urllib.request; a = json.loads(urllib.request.urlopen('https://server.duinocoin.com/getPool').read()); print(a)"```

**Comment by iiikary** [comment]
```
root@LEDE:~# python3 -c "import json; import urllib.request; a = json.loads(urllib.request.urlopen('https://server.duinocoin.com/getPool').read()); print(a)"
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:749)>
root@LEDE:~#

```

**Comment by BastelPichi** [comment]
try to run 
```opkg update
opkg upgrade openssl```

**Comment by iiikary** [comment]
![image](https://user-images.githubusercontent.com/65255663/148422633-b9eb7c34-60e8-4f71-b16b-160099ad7d61.png)

**Comment by BastelPichi** [comment]
use ```libopenssl```

**Comment by BastelPichi** [comment]
try ```opkg upgrade libopenssl```

**Comment by iiikary** [comment]
![image](https://user-images.githubusercontent.com/65255663/148423324-1b1f563b-5ae4-44b1-bdd5-a2b2549fcf21.png)

**Comment by BastelPichi** [comment]
Try the following commands. 
```opkg remove luci-ssl libustream-wolfssl```
```opkg install libopenssl libustream-openssl luci-ssl-openssl```

**Comment by iiikary** [comment]
![image](https://user-images.githubusercontent.com/65255663/148424904-8e338d99-7856-4aaf-9ff9-cc951c6ce3d8.png)

**Comment by BastelPichi** [comment]
hmmm... weird. Try upgrading your openwrt in the webinterface, or wait for m to find a souloution.

**Comment by iiikary** [comment]
thanks friend, for the help

**Comment by BastelPichi** [comment]
Has this fixed it?

**Comment by iiikary** [comment]
not yet, I will reinstall openwrt I will try older versions

**Comment by BastelPichi** [comment]
Older Versions wont fix this. What version are you using?

**Comment by BastelPichi** [comment]
Hey,
found a tenporary solioution. Gimme one minute to test.

**Comment by iiikary** [comment]
openwrt 17.0.1.4

**Comment by BastelPichi** [comment]
this code should work for now: 
`#!/usr/bin/env python3
# Router Miner, created by BastelPichi.
# Modifications made by ihyoudou
import hashlib
import os
import socket
import sys
import time
import urllib.request
import json
import ssl

soc = socket.socket()
soc.settimeout(10)

username = "Pichi"  # Edit this to your username, mind the quotes

enableLEDNotification = False # Edit this to enable or disable LED notification (True/False)
ledaccepted = "fritz4040:amber:info" # Edit this to your first LED name, leave as is if you disabled led notifications above.
ledrejected = "fritz4040:red:info" # Edit this to your second LED, leave as is if you disabled led notifications above.

def retrieve_server_ip():
    print("Retrieving Pool Address And Port")
    pool_obtained = False
    while not pool_obtained:
        try:
            serverip = ("https://server.duinocoin.com/getPool")
            # Loading pool address from API as json array
            poolInfo = json.loads(urllib.request.urlopen(serverip, context=ssl._create_unverified_context()).read())
            
            global pool_address, pool_port
            # Line 1 = IP
            pool_address = poolInfo['ip']
            # Line 2 = port
            pool_port = poolInfo['port']
            pool_obtained =  True
        except:
            print("> Failed to retrieve Pool Address and Port, Retrying.")
            continue

retrieve_server_ip()
while True:
    try:
        # This section connects and logs user to the server
        soc.connect((str(pool_address), int(pool_port)))
        server_version = soc.recv(3).decode()  # Get server version
        print("Server is on version", server_version)

        # Mining section
        while True:
            # Send job request 
            soc.send(bytes(
                "JOB,"
                + str(username)
                + ",LOW",
                encoding="utf8"))

            # Receive work
            job = soc.recv(1024).decode().rstrip("\n")
            # Split received data to job and difficulty
            job = job.split(",")
            difficulty = job[2]
            
            hashingStartTime = time.time()
            base_hash = hashlib.sha1(str(job[0]).encode('ascii'))
            temp_hash = None
            
            for result in range(100 * int(difficulty) + 1):
                # Calculate hash with difficulty
                temp_hash =  base_hash.copy()
                temp_hash.update(str(result).encode('ascii'))
                ducos1 = temp_hash.hexdigest()

                # If hash is even with expected hash result
                if job[1] == ducos1:
                    hashingStopTime = time.time()
                    timeDifference = hashingStopTime - hashingStartTime
                    hashrate = result / timeDifference

                    # Send numeric result to the server
                    soc.send(bytes(
                        str(result)
                        + ","
                        + str(hashrate)
                        + ",Router_Miner"
                        + "2.45",
                        encoding="utf8"))

                    # Get feedback about the result
                    feedback = soc.recv(1024).decode().rstrip("\n")
                    # If result was good
                    if feedback == "GOOD":
                        # If LED notification is enabled
                        if enableLEDNotification:
                            file = open(f'/sys/class/leds/{ledaccepted}/brightness','w')
                            file.write('1')
                            file.close()
                            time.sleep(0.3)
                            file = open(f'/sys/class/leds/{ledaccepted}/brightness','w')
                            file.write('0')
                            file.close()
                        print("Accepted share",
                              result,
                              "Hashrate",
                              int(hashrate/1000),
                              "kH/s",
                              "Difficulty",
                              difficulty)
                        break
                    # If result was incorrect
                    elif feedback == "BAD":
                        # If LED notification is enabled
                        if enableLEDNotification:
                            file = open(f'/sys/class/leds/{ledrejected}/brightness','w')
                            file.write('1')
                            file.close()
                            time.sleep(0.3)
                            file = open(f'/sys/class/leds/{ledrejected}/brightness','w')
                            file.write('0')
                            file.close()

                        print("Rejected share",
                              result,
                              "Hashrate",
                              int(hashrate/1000),
                              "kH/s",
                              "Difficulty",
                              difficulty)
                        break

    except Exception as e:
        print("Error occured: " + str(e) + ", restarting in 5s.")
        retrieve_server_ip()
        time.sleep(5)
        os.execl(sys.executable, sys.executable, *sys.argv)`

**Comment by BastelPichi** [comment]
Cool!

**Comment by iiikary** [comment]
![image](https://user-images.githubusercontent.com/65255663/148431448-f9a67a04-2ec0-4c47-9940-45602049b051.png)
