### ISSUE TITLE
GL-iNet Mango (GL-MT300N-V2) with OpenWrt 21.02 TIMEOUT

### ISSUE THREAD

**Issue by duckati** [BastelPichi/MineCryptoOnWifiRouter#7]
On GL-iNet Mango (GL-MT300N-V2) with OpenWrt 21.02 when I execute the command "python3 miner.py" the reply is:

> Retrieving Pool Address And Port
Error occured: timed out, restarting in 5s.

If I ping Google DNS the reply is:

> PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=113 time=38.536 ms

So the connectivity is ok

**Comment by BastelPichi** [comment]
Try pinging google.com

**Comment by BastelPichi** [comment]
And ping server.duinocoin.com and curl https://server.duinocoin.com/getPool ?

**Comment by duckati** [comment]
ping server.duinocoin.com not working, no reply:
 ![image](https://user-images.githubusercontent.com/51483537/168092213-300e9a8f-bb02-49c9-a1db-ed6d83429f48.png)
curl https://server.duinocoin.com/getPool seems working:
![image](https://user-images.githubusercontent.com/51483537/168093785-13b7f7ee-eed0-4615-a463-30a16de43f50.png)

Thanks

**Comment by BastelPichi** [comment]
hmmmmm. Weird. For me the minern works, so the code isnt the problem, and you can access the server. Very weird. WIll look into this later.

**Comment by zain141** [comment]
I'm also facing that same error.

**Comment by BastelPichi** [comment]
Please reopen if still up to date.

**Comment by XWKirya** [comment]
The problem is...


root@OpenWrt:~# python3 miner.py
Traceback (most recent call last):
  File "miner.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by BastelPichi** [comment]
> I am using NeWifi 3D2 Router, [Powered by LuCI openwrt-19.07 branch (git-21.044.30835-34e0d65)](https://github.com/openwrt/luci) / OpenWrt 19.07.7 r11306-c4a6851c72
> 
> The problem is...
> 
> root@OpenWrt:~# python3 miner.py Traceback (most recent call last): File "miner.py", line 11, in import requests ModuleNotFoundError: No module named 'requests'

This is not the right place, but all you need is to execute:
`python3 -m pip install requests`

**Comment by XWKirya** [comment]
It say's

"No module named pip"

in putty ***@***.***

**Comment by XWKirya** [comment]
I'll rewrite it based on google, there's python3-pip

opkg install python3-pip

**Comment by XWKirya** [comment]
Why the Router is not showing in Duino-Coin | Web Wallet MINERS

I can't see the router, It is working in putty showing hashrates but not showing in MINERS section in the Web.

**Comment by BastelPichi** [comment]
> Why the Router is not showing in Duino-Coin | Web Wallet MINERS
> 
> I can't see the router, It is working in putty showing hashrates but not showing in MINERS section in the Web.

It should need 5 shares to be shown. If not, check you mining key & username.

**Comment by XWKirya** [comment]
what fix?

**Comment by XWKirya** [comment]
Mining shares is okay.. five now but still not showing in Web. I check my
username and it is right.

"Username:mining key"

right?

**Comment by BastelPichi** [comment]
DuinoCoin changed the API. SHould be fixed very soon. Not my issue tho.
