### ISSUE TITLE
Errno32 Broken pipe error

### ISSUE THREAD

**Issue by MerGr** [BastelPichi/MineCryptoOnWifiRouter#9]
I'm running the script on a TP Link MR3020, it mines a few times before it spits out an error and restarts the script. Error 32 Broken pipe error
![image](https://user-images.githubusercontent.com/74867771/226338289-6a9f6dfa-9642-4f22-a0ec-6687f5377066.png)

**Comment by BastelPichi** [comment]
Somehow the image doesnt load for me - could you maybe paste the whole traceback?

**Comment by MerGr** [comment]
![IMG_20230320_173337.jpg](https://user-images.githubusercontent.com/74867771/226421617-717f7592-e38c-4730-8da2-c27fcfd5c177.jpg)

Is this what you mean ?

**Comment by BastelPichi** [comment]
This is quite weird. Broken Pipe means that theres been some error connecting to the server. Im not quite sure why this is happening. COuld you check how fast your internet is?

**Comment by MerGr** [comment]
My internet is 100Mbps Down 50 Mbps up, the MR3020 is hooked to the router via Ethernet

**Comment by BastelPichi** [comment]
> My internet is 100Mbps Down 50 Mbps up, the MR3020 is hooked to the router via Ethernet

no, like actually do a speedtest. However I dont think thats the problem.
Could you try to start with a lower diff tier cast? In the code, replace LOW with AVR. However revox aint gonna like you for this...

However, still I dont think that will fix it
